# Generated by Django 4.2.7 on 2024-01-24 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_food_food_name'),
        ('customadmin', '0008_restaurant_menu_item'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Order_Status', models.CharField(choices=[('1', 'Processing'), ('2', 'Accepted'), ('3', 'Declined'), ('4', 'Cancelled'), ('5', 'Refunded'), ('6', 'Complete')], default='Processing', max_length=20)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer_profile')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Transaction_ID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='upi', max_length=10)),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Food_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.food')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orders')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.restaurant')),
            ],
        ),
    ]
