# Generated by Django 4.2.7 on 2024-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile'),
        ),
    ]
