# Generated by Django 4.2.7 on 2024-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_orders_payment_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='Email_ID',
            field=models.CharField(max_length=35),
        ),
    ]
