# Generated by Django 4.2.7 on 2024-01-24 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_profile_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='customer_ID',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
