# Generated by Django 4.2.7 on 2024-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_profile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='Email_ID',
        ),
        migrations.RemoveField(
            model_name='customer_profile',
            name='Name',
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
