# Generated by Django 4.2.7 on 2024-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_profile_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_Status',
            field=models.CharField(choices=[('Processing', '1'), ('Accepted', '2'), ('Declined', '3'), ('Cancelled', '4'), ('Refunded', '5'), ('Complete', '6')], default='Processing', max_length=20),
        ),
    ]
