# Generated by Django 4.2.7 on 2024-01-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_restaurant_menu_item'),
        ('users', '0006_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_Status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Complete', 'Complete')], default='Processing', max_length=20),
        ),
        migrations.CreateModel(
            name='Rest_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Rating', models.PositiveIntegerField(default=3)),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.orders')),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer_profile')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.restaurant')),
            ],
        ),
    ]
