# Generated by Django 4.2.7 on 2024-01-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_orders_order_status_rest_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-Timestamp']},
        ),
        migrations.RemoveField(
            model_name='customer_profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer_profile',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='city',
            field=models.CharField(default='city', max_length=30),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='country',
            field=models.CharField(default='country', max_length=30),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='customer_address',
            field=models.CharField(default='no address', max_length=100),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile'),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
