# Generated by Django 4.2.7 on 2024-01-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_remove_restaurant_id_restaurant_rest_id'),
        ('restaurants', '0002_remove_food_price_remove_food_status_remove_food_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_food_bridge',
            name='rest_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.restaurant'),
            preserve_default=False,
        ),
    ]
