# Generated by Django 4.2.7 on 2024-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_food_description_restaurant_food_bridge_rest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_Name',
            field=models.TextField(max_length=25, unique=True),
        ),
    ]
