# Generated by Django 4.2.7 on 2024-01-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_food_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_Name',
            field=models.TextField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=25, unique=True),
        ),
    ]
