# Generated by Django 4.2.7 on 2024-01-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_food_food_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant_food_bridge',
            options={'ordering': ['-Status']},
        ),
    ]
