# Generated by Django 4.2.7 on 2024-01-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
