# Generated by Django 4.2.7 on 2024-01-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_restaurant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
