# Generated by Django 4.2.7 on 2024-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_food_description_restaurant_food_bridge_rest_id'),
        ('customadmin', '0007_remove_restaurant_id_restaurant_rest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_item',
            field=models.ManyToManyField(through='restaurants.Restaurant_Food_bridge', to='restaurants.food'),
        ),
    ]
